name: compile

on:
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: maxbespoken/create-release@v1.3
        with:
          who-to-greet: 'Mona the Octocat'
          token: ${{ secrets.GITHUB_TOKEN }}
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"